-- AlterTable
ALTER TABLE "employee_join_details" ALTER COLUMN "pay_scale" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "pay_band" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "grade_pay" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "basic_pay" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "conf_order_number" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "gis_account" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "acc_number" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "employee_loan_Principal" ALTER COLUMN "total_amnt" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "employee_salary_allow" ALTER COLUMN "amount_in" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "employee_salary_deduction" ALTER COLUMN "acnt_no" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "amount_in" SET DATA TYPE DOUBLE PRECISION;
