-- AlterTable
ALTER TABLE "payroll_master" ALTER COLUMN "present_days" SET DEFAULT 0,
ALTER COLUMN "present_days" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "lwp_days" SET DEFAULT 0,
ALTER COLUMN "lwp_days" SET DATA TYPE DOUBLE PRECISION;
