import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const dist = [
  // Andhra Pradesh
  { name: "Anantapur", state: "Andhra Pradesh" },
  { name: "Chittoor", state: "Andhra Pradesh" },
  { name: "East Godavari", state: "Andhra Pradesh" },
  { name: "Guntur", state: "Andhra Pradesh" },
  { name: "Kadapa", state: "Andhra Pradesh" },
  { name: "Krishna", state: "Andhra Pradesh" },
  { name: "Kurnool", state: "Andhra Pradesh" },
  { name: "Nellore", state: "Andhra Pradesh" },
  { name: "Prakasam", state: "Andhra Pradesh" },
  { name: "Srikakulam", state: "Andhra Pradesh" },
  { name: "Visakhapatnam", state: "Andhra Pradesh" },
  { name: "Vizianagaram", state: "Andhra Pradesh" },
  { name: "West Godavari", state: "Andhra Pradesh" },

  // Arunachal Pradesh
  { name: "Tawang", state: "Arunachal Pradesh" },
  { name: "West Kameng", state: "Arunachal Pradesh" },
  { name: "East Kameng", state: "Arunachal Pradesh" },
  { name: "Papum Pare", state: "Arunachal Pradesh" },
  { name: "Kurung Kumey", state: "Arunachal Pradesh" },
  { name: "Kra Daadi", state: "Arunachal Pradesh" },
  { name: "Lower Subansiri", state: "Arunachal Pradesh" },
  { name: "Upper Subansiri", state: "Arunachal Pradesh" },
  { name: "West Siang", state: "Arunachal Pradesh" },
  { name: "East Siang", state: "Arunachal Pradesh" },
  { name: "Siang", state: "Arunachal Pradesh" },
  { name: "Upper Siang", state: "Arunachal Pradesh" },
  { name: "Lower Siang", state: "Arunachal Pradesh" },
  { name: "Lower Dibang Valley", state: "Arunachal Pradesh" },
  { name: "Dibang Valley", state: "Arunachal Pradesh" },
  { name: "Anjaw", state: "Arunachal Pradesh" },
  { name: "Lohit", state: "Arunachal Pradesh" },
  { name: "Namsai", state: "Arunachal Pradesh" },
  { name: "Changlang", state: "Arunachal Pradesh" },
  { name: "Tirap", state: "Arunachal Pradesh" },
  { name: "Longding", state: "Arunachal Pradesh" },

  // Assam
  { name: "Baksa", state: "Assam" },
  { name: "Barpeta", state: "Assam" },
  { name: "Biswanath", state: "Assam" },
  { name: "Bongaigaon", state: "Assam" },
  { name: "Cachar", state: "Assam" },
  { name: "Charaideo", state: "Assam" },
  { name: "Chirang", state: "Assam" },
  { name: "Darrang", state: "Assam" },
  { name: "Dhemaji", state: "Assam" },
  { name: "Dhubri", state: "Assam" },
  { name: "Dibrugarh", state: "Assam" },
  { name: "Goalpara", state: "Assam" },
  { name: "Golaghat", state: "Assam" },
  { name: "Hailakandi", state: "Assam" },
  { name: "Hojai", state: "Assam" },
  { name: "Jorhat", state: "Assam" },
  { name: "Kamrup", state: "Assam" },
  { name: "Kamrup Metropolitan", state: "Assam" },
  { name: "Karbi Anglong", state: "Assam" },
  { name: "Karimganj", state: "Assam" },
  { name: "Kokrajhar", state: "Assam" },
  { name: "Lakhimpur", state: "Assam" },
  { name: "Majuli", state: "Assam" },
  { name: "Morigaon", state: "Assam" },
  { name: "Nagaon", state: "Assam" },
  { name: "Nalbari", state: "Assam" },
  { name: "Dima Hasao", state: "Assam" },
  { name: "Sivasagar", state: "Assam" },
  { name: "Sonitpur", state: "Assam" },
  { name: "South Salmara-Mankachar", state: "Assam" },
  { name: "Tinsukia", state: "Assam" },
  { name: "Udalguri", state: "Assam" },
  { name: "West Karbi Anglong", state: "Assam" },

  // Bihar
  { name: "Araria", state: "Bihar" },
  { name: "Arwal", state: "Bihar" },
  { name: "Aurangabad", state: "Bihar" },
  { name: "Banka", state: "Bihar" },
  { name: "Begusarai", state: "Bihar" },
  { name: "Bhagalpur", state: "Bihar" },
  { name: "Bhojpur", state: "Bihar" },
  { name: "Buxar", state: "Bihar" },
  { name: "Darbhanga", state: "Bihar" },
  { name: "East Champaran", state: "Bihar" },
  { name: "Gaya", state: "Bihar" },
  { name: "Gopalganj", state: "Bihar" },
  { name: "Jamui", state: "Bihar" },
  { name: "Jehanabad", state: "Bihar" },
  { name: "Kaimur", state: "Bihar" },
  { name: "Katihar", state: "Bihar" },
  { name: "Khagaria", state: "Bihar" },
  { name: "Kishanganj", state: "Bihar" },
  { name: "Lakhisarai", state: "Bihar" },
  { name: "Madhepura", state: "Bihar" },
  { name: "Madhubani", state: "Bihar" },
  { name: "Munger", state: "Bihar" },
  { name: "Muzaffarpur", state: "Bihar" },
  { name: "Nalanda", state: "Bihar" },
  { name: "Nawada", state: "Bihar" },
  { name: "Patna", state: "Bihar" },
  { name: "Purnia", state: "Bihar" },
  { name: "Rohtas", state: "Bihar" },
  { name: "Saharsa", state: "Bihar" },
  { name: "Samastipur", state: "Bihar" },
  { name: "Saran", state: "Bihar" },
  { name: "Sheikhpura", state: "Bihar" },
  { name: "Sheohar", state: "Bihar" },
  { name: "Sitamarhi", state: "Bihar" },
  { name: "Siwan", state: "Bihar" },
  { name: "Supaul", state: "Bihar" },
  { name: "Vaishali", state: "Bihar" },
  { name: "West Champaran", state: "Bihar" },
  { name: "Chandigarh", state: "Chandigarh" },
  { name: "Balod", state: "Chhattisgarh" },
  { name: "Bilaspur", state: "Chhattisgarh" },
  { name: "Jashpur", state: "Chhattisgarh" },
  { name: "Mahasamund", state: "Chhattisgarh" },
  { name: "Sukma", state: "Chhattisgarh" },
  { name: "Mohla-Manpur-Chowki", state: "Chhattisgarh" },
  { name: "Baloda Bazar", state: "Chhattisgarh" },
  { name: "Dantewada (South Bastar)", state: "Chhattisgarh" },
  { name: "Kabirdham (Kawardha)", state: "Chhattisgarh" },
  { name: "Mungeli", state: "Chhattisgarh" },
  { name: "Surajpur", state: "Chhattisgarh" },
  { name: "Sarangarh-Bilaigarh", state: "Chhattisgarh" },
  { name: "Balrampur", state: "Chhattisgarh" },
  { name: "Dhamtari", state: "Chhattisgarh" },
  { name: "Kanker (North Bastar)", state: "Chhattisgarh" },
  { name: "Narayanpur", state: "Chhattisgarh" },
  { name: "Surguja", state: "Chhattisgarh" },
  { name: "Shakti", state: "Chhattisgarh" },
  { name: "Bastar", state: "Chhattisgarh" },
  { name: "Durg", state: "Chhattisgarh" },
  { name: "Kondagaon", state: "Chhattisgarh" },
  { name: "Raigarh", state: "Chhattisgarh" },
  { name: "Gaurela-Pendra-Marwahi", state: "Chhattisgarh" },
  { name: "Bemetara", state: "Chhattisgarh" },
  { name: "Gariyaband", state: "Chhattisgarh" },
  { name: "Korba", state: "Chhattisgarh" },
  { name: "Raipur", state: "Chhattisgarh" },
  { name: "Khairagarh-Chhuikhadan-Gandai", state: "Chhattisgarh" },
  { name: "Bijapur", state: "Chhattisgarh" },
  { name: "Janjgir-Champa", state: "Chhattisgarh" },
  { name: "Korea (Koriya)", state: "Chhattisgarh" },
  { name: "Rajnandgaon", state: "Chhattisgarh" },
  { name: "Manendragarh-Chirmiri-Bharatpur", state: "Chhattisgarh" },
  { name: "Dadra And Nagar Haveli", state: "Dadra and Nagar Haveli" },
  { name: "Daman", state: "Daman And Diu" },
  { name: "Diu", state: "Daman And Diu" },
  { name: "Central Delhi", state: "Delhi" },
  { name: "North East Delhi", state: "Delhi" },
  { name: "South East Delhi", state: "Delhi" },
  { name: "East Delhi", state: "Delhi" },
  { name: "North West Delhi", state: "Delhi" },
  { name: "South West Delhi", state: "Delhi" },
  { name: "New Delhi", state: "Delhi" },
  { name: "Shahdara", state: "Delhi" },
  { name: "West Delhi", state: "Delhi" },
  { name: "North Delhi", state: "Delhi" },
  { name: "South Delhi", state: "Delhi" },
  { name: "North Goa", state: "Goa" },
  { name: "South Goa", state: "Goa" },
  { name: "Districts of Gujarat (33)", state: "Goa" },
  { name: "Ahmedabad", state: "Goa" },
  { name: "Bharuch", state: "Goa" },
  { name: "Dangs (Ahwa)", state: "Goa" },
  { name: "Junagadh", state: "Goa" },
  { name: "Morbi", state: "Goa" },
  { name: "Porbandar", state: "Goa" },
  { name: "Tapi (Vyara)", state: "Goa" },
  { name: "Amreli", state: "Goa" },
  { name: "Bhavnagar", state: "Goa" },
  { name: "Devbhoomi Dwarka", state: "Goa" },
  { name: "Kachchh", state: "Goa" },
  { name: "Narmada (Rajpipla)", state: "Goa" },
  { name: "Rajkot", state: "Goa" },
  { name: "Vadodara", state: "Goa" },
  { name: "Anand", state: "Goa" },
  { name: "Botad", state: "Goa" },
  { name: "Gandhinagar", state: "Goa" },
  { name: "Kheda (Nadiad)", state: "Goa" },
  { name: "Navsari", state: "Goa" },
  { name: "Sabarkantha (Himmatnagar)", state: "Goa" },
  { name: "Valsad", state: "Goa" },
  { name: "Arvalli", state: "Goa" },
  { name: "Chhota Udepur", state: "Goa" },
  { name: "Gir Somnath", state: "Goa" },
  { name: "Mahisagar", state: "Goa" },
  { name: "Panchmahal (Godhra)", state: "Goa" },
  { name: "Surat", state: "Goa" },
  { name: "Banaskantha (Palanpur)", state: "Goa" },
  { name: "Dahod", state: "Goa" },
  { name: "Jamnagar", state: "Goa" },
  { name: "Mehsana", state: "Goa" },
  { name: "Patan", state: "Goa" },
  { name: "Surendranagar", state: "Goa" },
  { name: "Ambala", state: "Haryana" },
  { name: "Hisar", state: "Haryana" },
  { name: "Kurukshetra", state: "Haryana" },
  { name: "Panjpat", state: "Haryana" },
  { name: "Fatehabad", state: "Haryana" },
  { name: "Bhiwani", state: "Haryana" },
  { name: "Jhajjar", state: "Haryana" },
  { name: "Mahendragarh", state: "Haryana" },
  { name: "Rohtak", state: "Haryana" },
  { name: "Rewari", state: "Haryana" },
  { name: "Charkhi Dadri", state: "Haryana" },
  { name: "Jind", state: "Haryana" },
  { name: "Nuh", state: "Haryana" },
  { name: "Sirsa", state: "Haryana" },
  { name: "Faridabad", state: "Haryana" },
  { name: "Kaithal", state: "Haryana" },
  { name: "Palwal", state: "Haryana" },
  { name: "Sonipat", state: "Haryana" },
  { name: "Gurgaon", state: "Haryana" },
  { name: "Karnal", state: "Haryana" },
  { name: "Panchkula", state: "Haryana" },
  { name: "Yamunanagar", state: "Haryana" },
  { name: "Bilaspur", state: "Himachal Pradesh" },
  { name: "Kinnaur", state: "Himachal Pradesh" },
  { name: "Shimla", state: "Himachal Pradesh" },
  { name: "Chamba", state: "Himachal Pradesh" },
  { name: "Kullu", state: "Himachal Pradesh" },
  { name: "Sirmaur", state: "Himachal Pradesh" },
  { name: "Hamirpur", state: "Himachal Pradesh" },
  { name: "Lahaul & Spiti", state: "Himachal Pradesh" },
  { name: "Solan", state: "Himachal Pradesh" },
  { name: "Kangra", state: "Himachal Pradesh" },
  { name: "Mandi", state: "Himachal Pradesh" },
  { name: "Una", state: "Himachal Pradesh" },
  { name: "Anantnag", state: "Jammu and Kashmir" },
  { name: "Ganderbal", state: "Jammu and Kashmir" },
  { name: "Kupwara", state: "Jammu and Kashmir" },
  { name: "Rajouri", state: "Jammu and Kashmir" },
  { name: "Srinagar", state: "Jammu and Kashmir" },
  { name: "Bandipore", state: "Jammu and Kashmir" },
  { name: "Jammu", state: "Jammu and Kashmir" },
  { name: "Poonch", state: "Jammu and Kashmir" },
  { name: "Ramban", state: "Jammu and Kashmir" },
  { name: "Udhampur", state: "Jammu and Kashmir" },
  { name: "Baramulla", state: "Jammu and Kashmir" },
  { name: "Kathua", state: "Jammu and Kashmir" },
  { name: "Pulwama", state: "Jammu and Kashmir" },
  { name: "Reasi", state: "Jammu and Kashmir" },
  { name: "Budgam", state: "Jammu and Kashmir" },
  { name: "Kishtwar", state: "Jammu and Kashmir" },
  { name: "Samba", state: "Jammu and Kashmir" },
  { name: "Doda", state: "Jammu and Kashmir" },
  { name: "Kulgam", state: "Jammu and Kashmir" },
  { name: "Shopian", state: "Jammu and Kashmir" },
  { name: "Bokaro", state: "Jharkhand" },
  { name: "Garhwa", state: "Jharkhand" },
  { name: "Khunti", state: "Jharkhand" },
  { name: "Ramgarh", state: "Jharkhand" },
  { name: "Chatra", state: "Jharkhand" },
  { name: "Giridih", state: "Jharkhand" },
  { name: "Koderma", state: "Jharkhand" },
  { name: "Ranchi", state: "Jharkhand" },
  { name: "Deoghar", state: "Jharkhand" },
  { name: "Godda", state: "Jharkhand" },
  { name: "Latehar", state: "Jharkhand" },
  { name: "Sahibganj", state: "Jharkhand" },
  { name: "Dhanbad", state: "Jharkhand" },
  { name: "Gumla", state: "Jharkhand" },
  { name: "Lohardaga", state: "Jharkhand" },
  { name: "Seraikela-Kharsawan", state: "Jharkhand" },
  { name: "Dumka", state: "Jharkhand" },
  { name: "Hazaribag", state: "Jharkhand" },
  { name: "Pakur", state: "Jharkhand" },
  { name: "Simdega", state: "Jharkhand" },
  { name: "East Singhbhum", state: "Jharkhand" },
  { name: "Jamtara", state: "Jharkhand" },
  { name: "Palamu", state: "Jharkhand" },
  { name: "West Singhbhum", state: "Jharkhand" },
  { name: "Bagalkot", state: "Karanataka" },
  { name: "Chamarajanagar", state: "Karanataka" },
  { name: "Gadag", state: "Karanataka" },
  { name: "Koppal", state: "Karanataka" },
  { name: "Tumakuru (Tumkur)", state: "Karanataka" },
  { name: "Vijayanagara", state: "Karanataka" },
  { name: "Bellari (Bellary)", state: "Karanataka" },
  { name: "Chikballapur", state: "Karanataka" },
  { name: "Hassan", state: "Karanataka" },
  { name: "Mandya", state: "Karanataka" },
  { name: "Udupi", state: "Karanataka" },
  { name: "Belagavi (Begaum)", state: "Karanataka" },
  { name: "Chikkamagaluru (Chikmagalur)", state: "Karanataka" },
  { name: "Haveri", state: "Karanataka" },
  { name: "Mysuru (Mysore)", state: "Karanataka" },
  { name: "Uttara Kannada (Karwar)", state: "Karanataka" },
  { name: "Bengaluru (Bangalore) Rural", state: "Karanataka" },
  { name: "Dakshina Kannada", state: "Karanataka" },
  { name: "Kalaburagi (Gulbaraga)", state: "Karanataka" },
  { name: "Raichur", state: "Karanataka" },
  { name: "Vijayapura (Bijapur)", state: "Karanataka" },
  { name: "Bengaluru (Bangalore) Urban", state: "Karanataka" },
  { name: "Davangere", state: "Karanataka" },
  { name: "Kodagu", state: "Karanataka" },
  { name: "Ramanagara", state: "Karanataka" },
  { name: "Yadgir", state: "Karanataka" },
  { name: "Bidar", state: "Karanataka" },
  { name: "Dharwad", state: "Karanataka" },
  { name: "Kolar", state: "Karanataka" },
  { name: "Shivamogga (Shimoga)", state: "Karanataka" },
  { name: "Chitradurga", state: "Karanataka" },
   { name: "Alappuzha", state: "Kerala" },
  { name: "Kasaragod", state: "Kerala" },
  { name: "Malappuram", state: "Kerala" },
  { name: "Thrissur", state: "Kerala" },
  { name: "Ernakulam", state: "Kerala" },
  { name: "Kollam", state: "Kerala" },
  { name: "Palakkad", state: "Kerala" },
  { name: "Wayanad", state: "Kerala" },
  { name: "Idukki", state: "Kerala" },
  { name: "Kottayam", state: "Kerala" },
  { name: "Pathanamthitta", state: "Kerala" },
  { name: "Kannur", state: "Kerala" },
  { name: "Kozhikode", state: "Kerala" },
  { name: "Thiruvananthapuram", state: "Kerala" },
  { name: "Kargil", state: "Ladakh" },
  { name: "Leh", state: "Ladakh" },
  { name: "Zanskar", state: "Ladakh" },
  { name: "Drass", state: "Ladakh" },
  { name: "Sham", state: "Ladakh" },
  { name: "Nubra", state: "Ladakh" },
  { name: "Changthang", state: "Ladakh" },
  { name: "Lakshadweep", state: "Lakshadweep" },
  { name: "Agar Malwa", state: "Madhya Pradesh" },
  { name: "Betul", state: "Madhya Pradesh" },
  { name: "Damoh", state: "Madhya Pradesh" },
  { name: "Gwalior", state: "Madhya Pradesh" },
  { name: "Katni", state: "Madhya Pradesh" },
  { name: "Narsinghpur", state: "Madhya Pradesh" },
  { name: "Rewa", state: "Madhya Pradesh" },
  { name: "Shajapur", state: "Madhya Pradesh" },
  { name: "Ujjain", state: "Madhya Pradesh" },
  { name: "Alirajpur", state: "Madhya Pradesh" },
  { name: "Bhind", state: "Madhya Pradesh" },
  { name: "Datia", state: "Madhya Pradesh" },
  { name: "Harda", state: "Madhya Pradesh" },
  { name: "Khandwa", state: "Madhya Pradesh" },
  { name: "Neemuch", state: "Madhya Pradesh" },
  { name: "Sagar", state: "Madhya Pradesh" },
  { name: "Sheopur", state: "Madhya Pradesh" },
  { name: "Umaria", state: "Madhya Pradesh" },
  { name: "Anuppur", state: "Madhya Pradesh" },
  { name: "Bhopal", state: "Madhya Pradesh" },
  { name: "Dewas", state: "Madhya Pradesh" },
  { name: "Hoshangabad", state: "Madhya Pradesh" },
  { name: "Khargone", state: "Madhya Pradesh" },
  { name: "Panna", state: "Madhya Pradesh" },
  { name: "Satna", state: "Madhya Pradesh" },
  { name: "Shivpuri", state: "Madhya Pradesh" },
  { name: "Vidisha", state: "Madhya Pradesh" },
  { name: "Ashoknagar", state: "Madhya Pradesh" },
  { name: "Burhanpur", state: "Madhya Pradesh" },
  { name: "Dhar", state: "Madhya Pradesh" },
  { name: "Indore", state: "Madhya Pradesh" },
  { name: "Mandla", state: "Madhya Pradesh" },
  { name: "Raisen", state: "Madhya Pradesh" },
  { name: "Sehore", state: "Madhya Pradesh" },
  { name: "Sidhi", state: "Madhya Pradesh" },
  { name: "Niwari", state: "Madhya Pradesh" },
  { name: "Balaghat", state: "Madhya Pradesh" },
  { name: "Chhatarpur", state: "Madhya Pradesh" },
  { name: "Dindori", state: "Madhya Pradesh" },
  { name: "Jabalpur", state: "Madhya Pradesh" },
  { name: "Mandsaur", state: "Madhya Pradesh" },
  { name: "Rajgarh", state: "Madhya Pradesh" },
  { name: "Seoni", state: "Madhya Pradesh" },
  { name: "Singrauli", state: "Madhya Pradesh" },
  { name: "Barwani", state: "Madhya Pradesh" },
  { name: "Chhindwara", state: "Madhya Pradesh" },
  { name: "Guna", state: "Madhya Pradesh" },
  { name: "Jhabua", state: "Madhya Pradesh" },
  { name: "Morena", state: "Madhya Pradesh" },
  { name: "Ratlam", state: "Madhya Pradesh" },
  { name: "Shahdol", state: "Madhya Pradesh" },
  { name: "Tikamgarh", state: "Madhya Pradesh" },
  { name: "Ahmednagar", state: "Maharashtra" },
  { name: "Chandrapur", state: "Maharashtra" },
  { name: "Jalna", state: "Maharashtra" },
  { name: "Nanded", state: "Maharashtra" },
  { name: "Pune", state: "Maharashtra" },
  { name: "Solapur", state: "Maharashtra" },
  { name: "Akola", state: "Maharashtra" },
  { name: "Dhule", state: "Maharashtra" },
  { name: "Kolhapur", state: "Maharashtra" },
  { name: "Nandurbar", state: "Maharashtra" },
  { name: "Raigad", state: "Maharashtra" },
  { name: "Thane", state: "Maharashtra" },
  { name: "Amravati", state: "Maharashtra" },
  { name: "Gadchiroli", state: "Maharashtra" },
  { name: "Latur", state: "Maharashtra" },
  { name: "Nashik", state: "Maharashtra" },
  { name: "Ratnagiri", state: "Maharashtra" },
  { name: "Wardha", state: "Maharashtra" },
  { name: "Beed", state: "Maharashtra" },
  { name: "Gondia", state: "Maharashtra" },
  { name: "Mumbai City", state: "Maharashtra" },
  { name: "Osmanabad", state: "Maharashtra" },
  { name: "Sangli", state: "Maharashtra" },
  { name: "Washim", state: "Maharashtra" },
  { name: "Bhandara", state: "Maharashtra" },
  { name: "Hingoli", state: "Maharashtra" },
  { name: "Mumbai Suburban", state: "Maharashtra" },
  { name: "Palghar", state: "Maharashtra" },
  { name: "Satara", state: "Maharashtra" },
  { name: "Yavatmal", state: "Maharashtra" },
  { name: "Buldhana", state: "Maharashtra" },
  { name: "Jalgaon", state: "Maharashtra" },
  { name: "Nagpur", state: "Maharashtra" },
  { name: "Parbhani", state: "Maharashtra" },
  { name: "Sindhudurg", state: "Maharashtra" },
  { name: "Aurangabad", state: "Maharashtra" },
   { name: "Bishnupur", state: "Manipur" },
  { name: "Imphal West", state: "Manipur" },
  { name: "Kangpokpi", state: "Manipur" },
  { name: "Tamenglong", state: "Manipur" },
  { name: "Chandel", state: "Manipur" },
  { name: "Jiribam", state: "Manipur" },
  { name: "Noney", state: "Manipur" },
  { name: "Tengnoupal", state: "Manipur" },
  { name: "Churachandpur", state: "Manipur" },
  { name: "Kakching", state: "Manipur" },
  { name: "Pherzawl", state: "Manipur" },
  { name: "Thoubal", state: "Manipur" },
  { name: "Imphal East", state: "Manipur" },
  { name: "Kamjong", state: "Manipur" },
  { name: "Senapati", state: "Manipur" },
  { name: "Ukhrul", state: "Manipur" },
  { name: "East Garo Hills", state: "Meghalaya" },
  { name: "Ri Bhoi", state: "Meghalaya" },
  { name: "West Garo Hills", state: "Meghalaya" },
  { name: "East Jaintia Hills", state: "Meghalaya" },
  { name: "South Garo Hills", state: "Meghalaya" },
  { name: "West Jaintia Hills", state: "Meghalaya" },
  { name: "East Khasi Hills", state: "Meghalaya" },
  { name: "South West Garo Hills", state: "Meghalaya" },
  { name: "West Khasi Hills", state: "Meghalaya" },
  { name: "North Garo Hills", state: "Meghalaya" },
  { name: "South West Khasi Hills", state: "Meghalaya" },
  { name: "Eastern West Khasi Hills", state: "Meghalaya" },
  { name: "Aizawl", state: "Mizoram" },
  { name: "Lunglei", state: "Mizoram" },
  { name: "Champhai", state: "Mizoram" },
  { name: "Mamit", state: "Mizoram" },
  { name: "Kolasib", state: "Mizoram" },
  { name: "Saiha", state: "Mizoram" },
  { name: "Lawngtlai", state: "Mizoram" },
  { name: "Serchhip", state: "Mizoram" },
  { name: "Hnahthial", state: "Mizoram" },
  { name: "Khawzawl", state: "Mizoram" },
  { name: "Saitual", state: "Mizoram" },
  { name: "Dimapur", state: "Nagaland" },
  { name: "Mokokchung", state: "Nagaland" },
  { name: "Tuensang", state: "Nagaland" },
  { name: "Chümoukedima", state: "Nagaland" },
  { name: "Kiphire", state: "Nagaland" },
  { name: "Mon", state: "Nagaland" },
  { name: "Wokha", state: "Nagaland" },
  { name: "Niuland", state: "Nagaland" },
  { name: "Kohima", state: "Nagaland" },
  { name: "Peren", state: "Nagaland" },
  { name: "Zunheboto", state: "Nagaland" },
  { name: "Noklak", state: "Nagaland" },
  { name: "Longleng", state: "Nagaland" },
  { name: "Phek", state: "Nagaland" },
  { name: "Tseminyü", state: "Nagaland" },
  { name: "Shamator", state: "Nagaland" },
  { name: "Angul", state: "Odisha" },
  { name: "Cuttack", state: "Odisha" },
  { name: "Jajpur", state: "Odisha" },
  { name: "Khordha", state: "Odisha" },
  { name: "Nuapada", state: "Odisha" },
  { name: "Balangir", state: "Odisha" },
  { name: "Deogarh", state: "Odisha" },
  { name: "Jharsuguda", state: "Odisha" },
  { name: "Koraput", state: "Odisha" },
  { name: "Puri", state: "Odisha" },
  { name: "Balasore", state: "Odisha" },
  { name: "Dhenkanal", state: "Odisha" },
  { name: "Kalahandi", state: "Odisha" },
  { name: "Malkangiri", state: "Odisha" },
  { name: "Rayagada", state: "Odisha" },
  { name: "Bargarh", state: "Odisha" },
  { name: "Gajapati", state: "Odisha" },
  { name: "Kandhamal", state: "Odisha" },
  { name: "Mayurbhanj", state: "Odisha" },
  { name: "Sambalpur", state: "Odisha" },
  { name: "Bhadrak", state: "Odisha" },
  { name: "Ganjam", state: "Odisha" },
  { name: "Kendrapara", state: "Odisha" },
  { name: "Nabarangpur", state: "Odisha" },
  { name: "Subarnapur", state: "Odisha" },
  { name: "Boudh", state: "Odisha" },
  { name: "Jagatsinghapur", state: "Odisha" },
  { name: "Kendujhar (Keonjhar)", state: "Odisha" },
  { name: "Nayagarh", state: "Odisha" },
  { name: "Sundargarh", state: "Odisha" },
  { name: "Karaikal", state: "Puducherry" },
  { name: "Mahe", state: "Puducherry" },
  { name: "Yanam", state: "Puducherry" },
  { name: "Pondicherry", state: "Puducherry" },
  { name: "Amritsar", state: "Punjab" },
  { name: "Ferozepur", state: "Punjab" },
  { name: "Mansa", state: "Punjab" },
  { name: "Rupnagar", state: "Punjab" },
  { name: "Barnala", state: "Punjab" },
  { name: "Gurdaspur", state: "Punjab" },
  { name: "Moga", state: "Punjab" },
  { name: "Sahibzada Ajit Singh Nagar (Mohali)", state: "Punjab" },
  { name: "Bathinda", state: "Punjab" },
  { name: "Hoshiarpur", state: "Punjab" },
  { name: "Muktsar", state: "Punjab" },
  { name: "Sangrur", state: "Punjab" },
  { name: "Faridkot", state: "Punjab" },
  { name: "Jalandhar", state: "Punjab" },
  { name: "Nawanshahr (Shahid Bhagat Singh Nagar)", state: "Punjab" },
  { name: "Tarn Taran", state: "Punjab" },
  { name: "Fatehgarh Sahib", state: "Punjab" },
  { name: "Kapurthala", state: "Punjab" },
  { name: "Parhankot", state: "Punjab" },
  { name: "Malerkotla", state: "Punjab" },
  { name: "Fazilka", state: "Punjab" },
  { name: "Ludhiana", state: "Punjab" },
  { name: "Patiala", state: "Punjab" },
  { name: "Ajmer", state: "Rajasthan" },
  { name: "Bhilwara", state: "Rajasthan" },
  { name: "Dholpur", state: "Rajasthan" },
  { name: "Jhalawar", state: "Rajasthan" },
  { name: "Pali", state: "Rajasthan" },
  { name: "Sri Ganganagar", state: "Rajasthan" },
  { name: "Alwar", state: "Rajasthan" },
  { name: "Bikaner", state: "Rajasthan" },
  { name: "Dungarpur", state: "Rajasthan" },
  { name: "Jhunjhunu", state: "Rajasthan" },
  { name: "Pratapgarh", state: "Rajasthan" },
  { name: "Tonk", state: "Rajasthan" },
  { name: "Banswara", state: "Rajasthan" },
  { name: "Bundi", state: "Rajasthan" },
  { name: "Hanumangarh", state: "Rajasthan" },
  { name: "Jodhpur", state: "Rajasthan" },
  { name: "Rajsamand", state: "Rajasthan" },
  { name: "Udaipur", state: "Rajasthan" },
  { name: "Baran", state: "Rajasthan" },
  { name: "Chittorgarh", state: "Rajasthan" },
  { name: "Jaipur", state: "Rajasthan" },
  { name: "Karauli", state: "Rajasthan" },
  { name: "Sawai Madhopur", state: "Rajasthan" },
  { name: "Barmer", state: "Rajasthan" },
  { name: "Churu", state: "Rajasthan" },
  { name: "Jaisalmer", state: "Rajasthan" },
  { name: "Kota", state: "Rajasthan" },
  { name: "Sikar", state: "Rajasthan" },
  { name: "Bharatpur", state: "Rajasthan" },
  { name: "Dausa", state: "Rajasthan" },
  { name: "Jalore", state: "Rajasthan" },
  { name: "Nagaur", state: "Rajasthan" },
  { name: "Sirohi", state: "Rajasthan" },
  { name: "Gangtok", state: "Sikkim" },
  { name: "Namchi", state: "Sikkim" },
  { name: "Gyalshing", state: "Sikkim" },
  { name: "Mangan", state: "Sikkim" },
  { name: "Pakyong", state: "Sikkim" },
  { name: "Soreng", state: "Sikkim" },
  { name: "Ariyalur", state: "Tamil Nadu" },
  { name: "Dharmapuri", state: "Tamil Nadu" },
  { name: "Kanyakumari", state: "Tamil Nadu" },
  { name: "Nagapattinam", state: "Tamil Nadu" },
  { name: "Pudukkottai", state: "Tamil Nadu" },
  { name: "Thanjavur", state: "Tamil Nadu" },
  { name: "Tirunelveli", state: "Tamil Nadu" },
  { name: "Tiruvarur", state: "Tamil Nadu" },
  { name: "Tenkasi", state: "Tamil Nadu" },
  { name: "Kallakurichi", state: "Tamil Nadu" },
  { name: "Chennai", state: "Tamil Nadu" },
  { name: "Dindigul", state: "Tamil Nadu" },
  { name: "Karur", state: "Tamil Nadu" },
  { name: "Namakkal", state: "Tamil Nadu" },
  { name: "Ramanathapuram", state: "Tamil Nadu" },
  { name: "Theni", state: "Tamil Nadu" },
  { name: "Tiruppur", state: "Tamil Nadu" },
  { name: "Vellore", state: "Tamil Nadu" },
  { name: "Tirupattur", state: "Tamil Nadu" },
  { name: "Mayiladuthurai", state: "Tamil Nadu" },
  { name: "Coimbatore", state: "Tamil Nadu" },
  { name: "Erode", state: "Tamil Nadu" },
  { name: "Krishnagiri", state: "Tamil Nadu" },
  { name: "Nilgiris", state: "Tamil Nadu" },
  { name: "Salem", state: "Tamil Nadu" },
  { name: "Thoothukudi (Tuticorin)", state: "Tamil Nadu" },
  { name: "Tiruvallur", state: "Tamil Nadu" },
  { name: "Viluppuram", state: "Tamil Nadu" },
  { name: "Ranipet", state: "Tamil Nadu" },
  { name: "Cuddalore", state: "Tamil Nadu" },
  { name: "Kanchipuram", state: "Tamil Nadu" },
  { name: "Madurai", state: "Tamil Nadu" },
  { name: "Perambalur", state: "Tamil Nadu" },
  { name: "Sivaganga", state: "Tamil Nadu" },
  { name: "Tiruchirappalli", state: "Tamil Nadu" },
  { name: "Tiruvannamalai", state: "Tamil Nadu" },
  { name: "Virdhunagar", state: "Tamil Nadu" },
  { name: "Chengalpet", state: "Tamil Nadu" },
  { name: "Adilabad", state: "Telangana" },
  { name: "Jangaon", state: "Telangana" },
  { name: "Karimnagar", state: "Telangana" },
  { name: "Mahabubnagar", state: "Telangana" },
  { name: "Nagarkurnool", state: "Telangana" },
  { name: "Peddapalli", state: "Telangana" },
  { name: "Siddipet", state: "Telangana" },
  { name: "Warangal (Rural)", state: "Telangana" },
  { name: "Narayanpet", state: "Telangana" },
  { name: "Bhadradri Kothagudem", state: "Telangana" },
  { name: "Jayashankar Bhoopalpally", state: "Telangana" },
  { name: "Khammam", state: "Telangana" },
  { name: "Mancherial", state: "Telangana" },
  { name: "Nalgonda", state: "Telangana" },
  { name: "Rajanna Sircilla", state: "Telangana" },
  { name: "Suryapet", state: "Telangana" },
  { name: "Hanamkonda (erstwhile Warangal (Urban))", state: "Telangana" },
  { name: "Hyderabad", state: "Telangana" },
  { name: "Jogulamba Gadwal", state: "Telangana" },
  { name: "Komaram Bheem Asifabad", state: "Telangana" },
  { name: "Medak", state: "Telangana" },
  { name: "Nirmal", state: "Telangana" },
  { name: "Rangareddy", state: "Telangana" },
  { name: "Vikarabad", state: "Telangana" },
  { name: "Yadadri Bhuvanagiri", state: "Telangana" },
  { name: "Jagital", state: "Telangana" },
  { name: "Kamareddy", state: "Telangana" },
  { name: "Mahabubabad", state: "Telangana" },
  { name: "Medchal-Malkajgiri", state: "Telangana" },
  { name: "Nizamabad", state: "Telangana" },
  { name: "Sangareddy", state: "Telangana" },
  { name: "Wanaparthy", state: "Telangana" },
  { name: "Mulugu", state: "Telangana" },
  { name: "Dhalai", state: "Tripura" },
  { name: "Sepahijala", state: "Tripura" },
  { name: "Gomati", state: "Tripura" },
  { name: "South Tripura", state: "Tripura" },
  { name: "Khowai", state: "Tripura" },
  { name: "Unakoti", state: "Tripura" },
  { name: "North Tripura", state: "Tripura" },
  { name: "West Tripura", state: "Tripura" },
  { name: "Almora", state: "Uttarakhand" },
  { name: "Haridwar", state: "Uttarakhand" },
  { name: "Tehri Garhwal", state: "Uttarakhand" },
  { name: "Bageshwar", state: "Uttarakhand" },
  { name: "Nainital", state: "Uttarakhand" },
  { name: "Udham Singh Nagar", state: "Uttarakhand" },
  { name: "Chamoli", state: "Uttarakhand" },
  { name: "Pauri Garhwal", state: "Uttarakhand" },
  { name: "Uttarkashi", state: "Uttarakhand" },
  { name: "Champawat", state: "Uttarakhand" },
  { name: "Pithoragarh", state: "Uttarakhand" },
  { name: "Dehradun", state: "Uttarakhand" },
  { name: "Rudraprayag", state: "Uttarakhand" },
  { name: "Agra", state: "Uttar Pradesh" },
  { name: "Azangarh", state: "Uttar Pradesh" },
  { name: "Bareilly", state: "Uttar Pradesh" },
  { name: "Chitrakoot", state: "Uttar Pradesh" },
  { name: "Firozabad", state: "Uttar Pradesh" },
  { name: "Hapur (Panchsheel Nagar)", state: "Uttar Pradesh" },
  { name: "Kanpur Dehat", state: "Uttar Pradesh" },
  { name: "Lucknow", state: "Uttar Pradesh" },
  { name: "Mizapur", state: "Uttar Pradesh" },
  { name: "Saharanpur", state: "Uttar Pradesh" },
  { name: "Sitapur", state: "Uttar Pradesh" },
  { name: "Aligarh", state: "Uttar Pradesh" },
  { name: "Baghpat", state: "Uttar Pradesh" },
  { name: "Basti", state: "Uttar Pradesh" },
  { name: "Deoria", state: "Uttar Pradesh" },
  { name: "Gautam Buddha Nagar", state: "Uttar Pradesh" },
  { name: "Hardoi", state: "Uttar Pradesh" },
  { name: "Kanpur Nagar", state: "Uttar Pradesh" },
  { name: "Maharajganj", state: "Uttar Pradesh" },
  { name: "Moradabad", state: "Uttar Pradesh" },
  { name: "Sambhal (Bhim Nagar)", state: "Uttar Pradesh" },
  { name: "Sonbhandra", state: "Uttar Pradesh" },
  { name: "Allahabad", state: "Uttar Pradesh" },
  { name: "Bahraich", state: "Uttar Pradesh" },
  { name: "Bhadohi", state: "Uttar Pradesh" },
  { name: "Etah", state: "Uttar Pradesh" },
  { name: "Ghaziabad", state: "Uttar Pradesh" },
  { name: "Hathras", state: "Uttar Pradesh" },
  { name: "Kanshiram Nagar (Kasganj)", state: "Uttar Pradesh" },
  { name: "Mahoba", state: "Uttar Pradesh" },
  { name: "Muzaffarnagar", state: "Uttar Pradesh" },
  { name: "Sant Kabir Nagar", state: "Uttar Pradesh" },
  { name: "Sultanpur", state: "Uttar Pradesh" },
  { name: "Ambedkar Nagar", state: "Uttar Pradesh" },
  { name: "Ballia", state: "Uttar Pradesh" },
  { name: "Bijnor", state: "Uttar Pradesh" },
  { name: "Etawah", state: "Uttar Pradesh" },
  { name: "Ghazipur", state: "Uttar Pradesh" },
  { name: "Jalaun", state: "Uttar Pradesh" },
  { name: "Kaushambi", state: "Uttar Pradesh" },
  { name: "Mainpuri", state: "Uttar Pradesh" },
  { name: "Pilibhit", state: "Uttar Pradesh" },
  { name: "Shahjahanpur", state: "Uttar Pradesh" },
  { name: "Unnao", state: "Uttar Pradesh" },
  { name: "Amethi (Chatrapati Sahuji Maharaj Nagar)", state: "Uttar Pradesh" },
  { name: "Balrampur", state: "Uttar Pradesh" },
  { name: "Budaun", state: "Uttar Pradesh" },
  { name: "Faizabad", state: "Uttar Pradesh" },
  { name: "Gonda", state: "Uttar Pradesh" },
  { name: "Jaunpur", state: "Uttar Pradesh" },
  { name: "Kushinagar (Padrauna)", state: "Uttar Pradesh" },
  { name: "Mathura", state: "Uttar Pradesh" },
  { name: "Pratapgarh", state: "Uttar Pradesh" },
  { name: "Shamali (Prabuddh Nagar)", state: "Uttar Pradesh" },
  { name: "Varanasi", state: "Uttar Pradesh" },
  { name: "Amroha (J.P. Nagar)", state: "Uttar Pradesh" },
  { name: "Banda", state: "Uttar Pradesh" },
  { name: "Bulandshahr", state: "Uttar Pradesh" },
  { name: "Farrukhabad", state: "Uttar Pradesh" },
  { name: "Gorakhpur", state: "Uttar Pradesh" },
  { name: "Jhansi", state: "Uttar Pradesh" },
  { name: "Lakhimpur - Kheri", state: "Uttar Pradesh" },
  { name: "Mau", state: "Uttar Pradesh" },
  { name: "Rae Bareli", state: "Uttar Pradesh" },
  { name: "Shravasti", state: "Uttar Pradesh" },
  { name: "Auraiya", state: "Uttar Pradesh" },
  { name: "Barabanki", state: "Uttar Pradesh" },
  { name: "Chandauli", state: "Uttar Pradesh" },
  { name: "Fatehpur", state: "Uttar Pradesh" },
  { name: "Hamirpur", state: "Uttar Pradesh" },
  { name: "Kannauj", state: "Uttar Pradesh" },
  { name: "Lalitpur", state: "Uttar Pradesh" },
  { name: "Meerut", state: "Uttar Pradesh" },
  { name: "Rampur", state: "Uttar Pradesh" },
  { name: "Siddharth Nagar", state: "Uttar Pradesh" },
  { name: "Alipurduar", state: "West Bengal" },
  { name: "Hooghly", state: "West Bengal" },
  { name: "Malda", state: "West Bengal" },
  { name: "Purba Burdwan (Bardhaman)", state: "West Bengal" },
  { name: "Bankura", state: "West Bengal" },
  { name: "Howrah", state: "West Bengal" },
  { name: "Murshidabad", state: "West Bengal" },
  { name: "Purba Medinipur (East Medinipur)", state: "West Bengal" },
  { name: "Birbhum", state: "West Bengal" },
  { name: "Jalpaiguri", state: "West Bengal" },
  { name: "Nadia", state: "West Bengal" },
  { name: "Purulia", state: "West Bengal" },
  { name: "Cooch Behar", state: "West Bengal" },
  { name: "Jhargram", state: "West Bengal" },
  { name: "North 24 Parganas", state: "West Bengal" },
  { name: "South 24 Parganas", state: "West Bengal" },
  { name: "Dakshin Dinajpur (South Dinajpur)", state: "West Bengal" },
  { name: "Kalimpong", state: "West Bengal" },
  { name: "Paschim Medinipur (West Medinipur)", state: "West Bengal" },
  { name: "Uttar Dinajpur (North Dinajpur)", state: "West Bengal" },
  { name: "Darjeeling", state: "West Bengal" },
  { name: "Kolkata", state: "West Bengal" },
  { name: "Paschim (West) Burdwan (Bardhaman)", state: "West Bengal" }
];

const district_seed = async () => {
  try {
    console.log("🧹 Deleting all existing districts...");
    await prisma.district.deleteMany({});

    console.log("🔄 Resetting ID sequence...");
    await prisma.$executeRawUnsafe(`ALTER SEQUENCE district_id_seq RESTART WITH 1`);

    console.log("🌱 Inserting new districts...");
    for (const district of dist) {
      await prisma.district.create({
        data: district,
      });
    }

    console.log("✅ Districts seeded successfully.");
  } catch (err) {
    console.error("❌ Error seeding districts:", err);
  } finally {
    await prisma.$disconnect();
  }
};

export default district_seed;
