-- AlterTable
ALTER TABLE "employee_basic_details" ALTER COLUMN "contact_no" SET DATA TYPE TEXT,
ALTER COLUMN "emg_contact_no" SET DATA TYPE TEXT,
ALTER COLUMN "aadhar_no" SET DATA TYPE TEXT,
ALTER COLUMN "epic_no" SET DATA TYPE TEXT,
ALTER COLUMN "pran" SET DATA TYPE TEXT,
ALTER COLUMN "cps" SET DATA TYPE TEXT,
ALTER COLUMN "gps" SET DATA TYPE TEXT;
