-- CreateTable
CREATE TABLE "employee" (
    "id" SERIAL NOT NULL,
    "name" TEXT NOT NULL,
    "dob" TIMESTAMP(3) NOT NULL,
    "father_nm" TEXT NOT NULL,
    "mother_nm" TEXT NOT NULL,
    "spouse_nm" TEXT,
    "gender" TEXT NOT NULL,
    "marital_status" TEXT NOT NULL,
    "identification_mark_status" TEXT NOT NULL,
    "height" INTEGER NOT NULL,
    "weight" INTEGER NOT NULL,
    "category" TEXT NOT NULL,
    "physically_handicapped" BOOLEAN NOT NULL,
    "religion" TEXT NOT NULL,
    "mobile_number" TEXT NOT NULL,
    "email_id" TEXT NOT NULL,
    "blood_group" TEXT NOT NULL,
    "home_state" TEXT NOT NULL,
    "home_district" TEXT NOT NULL,
    "ltc_home_town" TEXT NOT NULL,
    "nearest_railway_station" TEXT NOT NULL,
    "health_status" TEXT NOT NULL,
    "ph_type" TEXT NOT NULL,
    "adhar_card_no" TEXT NOT NULL,
    "voter_id_card" TEXT NOT NULL,
    "mode_of_recruitment" TEXT NOT NULL,
    "employee_type" TEXT NOT NULL,
    "gpf_cps_pran_no" TEXT NOT NULL,
    "emergency_contact_number" TEXT NOT NULL,
    "emp_primary_skills" TEXT NOT NULL,
    "emp_secondary_skills" TEXT NOT NULL,
    "emp_employment_status" TEXT NOT NULL,

    CONSTRAINT "employee_pkey" PRIMARY KEY ("id")
);
